
show-fixes = true
target-version = "py312"

[lint]
select = ["E", "F", "D"]
ignore = ["D212"]
extend-select = []
pydocstyle.convention = "google"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "lf"
